### ISSUE TITLE
Hi !! Perl executing problems !

### ISSUE THREAD

**Issue by demostenes1509** [rghose/kill-close-wait-connections#1]
Im running your script, and Im getting this error:

Can't locate Net/Pcap.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.10.1 /usr/local/share/perl/5.10.1 /usr/lib/perl5 /usr/share
/perl5 /usr/lib/perl/5.10 /usr/share/perl/5.10 /usr/local/lib/site_perl .) at maxi.pl line 3.
BEGIN failed--compilation aborted at maxi.pl line 3.

Would you mind helping me ?

Thanks !

**Comment by rghose** [comment]
You would need to install Net::Pcap library. Take a look here for an operating system based package:
http://stackoverflow.com/questions/22318522/cant-install-netpcap-module

Alternatively, you can also use cpan to install the library. This should fix your issue!
