### ISSUE TITLE
undefined symbol: Perl_Gthr_key_ptr error

### ISSUE THREAD

**Issue by ikryptoknight** [rghose/kill-close-wait-connections#10]
Hi Team,

I am getting the below error while running the perl script.

kill-close-wait-connections]$ ./kill_close_wait_connections.pl
/usr/bin/perl: symbol lookup error: /usr/lib64/perl5/vendor_perl/auto/Net/RawIP/RawIP.so: undefined symbol: Perl_Gthr_key_ptr
@terwey @rghose @basil-lion 
Need your suggestion to resolve the issue.

**Comment by rghose** [comment]
What is your perl version? This generally happens if your perl setup isn't valid
