### ISSUE TITLE
Fails for IPv6 addresses

### ISSUE THREAD

**Issue by The4thLaw** [rghose/kill-close-wait-connections#6]
This script fails for IPv6 addresses. The `sed` command will replace the : by spaces and make the addresses unparseable, resulting in errors like
```
host_to_ip: failed at /usr/local/lib64/perl5/Net/RawIP.pm line 480, <$CONNECTIONS_WAIT> line 1
```

I got a very ugly workaround by doing:
```
open(my $CONNECTIONS_WAIT, "netstat -tulnap | grep CLOSE_WAIT | awk '{print \$4,\" \",\$5}' | grep -vE '^::1:[0-9]' | sed 's/^::ffff://;s/\\W::ffff://;s/:/ /g' |") || die "Failed: $!\n";
```

It may help people but I'm definitely not sending a pull request for something like that...

**Comment by basil-lion** [comment]
Dirty fix provided in pull request #7 
(the only thing it does is just strips off ipv6 header from netstat output, if found)

**Comment by rghose** [comment]
thanks @basil-lion  for the PR. I have merged it. Does this still occur?

**Comment by basil-lion** [comment]
Works fine now. Thanks!
